/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { NutritionPhaseWhereInput } from "./NutritionPhaseWhereInput";
import { Type } from "class-transformer";
import { NutritionPhaseOrderByInput } from "./NutritionPhaseOrderByInput";

@ArgsType()
class NutritionPhaseFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => NutritionPhaseWhereInput,
  })
  @Field(() => NutritionPhaseWhereInput, { nullable: true })
  @Type(() => NutritionPhaseWhereInput)
  where?: NutritionPhaseWhereInput;

  @ApiProperty({
    required: false,
    type: NutritionPhaseOrderByInput,
  })
  @Field(() => NutritionPhaseOrderByInput, { nullable: true })
  @Type(() => NutritionPhaseOrderByInput)
  orderBy?: NutritionPhaseOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { NutritionPhaseFindManyArgs };
