/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateNutritionPlanArgs } from "./CreateNutritionPlanArgs";
import { UpdateNutritionPlanArgs } from "./UpdateNutritionPlanArgs";
import { DeleteNutritionPlanArgs } from "./DeleteNutritionPlanArgs";
import { NutritionPlanFindManyArgs } from "./NutritionPlanFindManyArgs";
import { NutritionPlanFindUniqueArgs } from "./NutritionPlanFindUniqueArgs";
import { NutritionPlan } from "./NutritionPlan";
import { TipFindManyArgs } from "../../tip/base/TipFindManyArgs";
import { Tip } from "../../tip/base/Tip";
import { Goal } from "../../goal/base/Goal";
import { NutritionPlanService } from "../nutritionPlan.service";

@graphql.Resolver(() => NutritionPlan)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class NutritionPlanResolverBase {
  constructor(
    protected readonly service: NutritionPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  async _nutritionPlansMeta(
    @graphql.Args() args: NutritionPlanFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [NutritionPlan])
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  async nutritionPlans(
    @graphql.Args() args: NutritionPlanFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "NutritionPlan",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => NutritionPlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "own",
  })
  async nutritionPlan(
    @graphql.Args() args: NutritionPlanFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "NutritionPlan",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => NutritionPlan)
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "create",
    possession: "any",
  })
  async createNutritionPlan(
    @graphql.Args() args: CreateNutritionPlanArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"NutritionPlan"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        goal: args.data.goal
          ? {
              connect: args.data.goal,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => NutritionPlan)
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "update",
    possession: "any",
  })
  async updateNutritionPlan(
    @graphql.Args() args: UpdateNutritionPlanArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"NutritionPlan"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          goal: args.data.goal
            ? {
                connect: args.data.goal,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => NutritionPlan)
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "delete",
    possession: "any",
  })
  async deleteNutritionPlan(
    @graphql.Args() args: DeleteNutritionPlanArgs
  ): Promise<NutritionPlan | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Tip])
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  async tips(
    @graphql.Parent() parent: NutritionPlan,
    @graphql.Args() args: TipFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tip",
    });
    const results = await this.service.findTips(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Goal, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  async goal(
    @graphql.Parent() parent: NutritionPlan,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Goal | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Goal",
    });
    const result = await this.service.getGoal(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
