/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { NutritionPlanService } from "../nutritionPlan.service";
import { NutritionPlanCreateInput } from "./NutritionPlanCreateInput";
import { NutritionPlanWhereInput } from "./NutritionPlanWhereInput";
import { NutritionPlanWhereUniqueInput } from "./NutritionPlanWhereUniqueInput";
import { NutritionPlanFindManyArgs } from "./NutritionPlanFindManyArgs";
import { NutritionPlanUpdateInput } from "./NutritionPlanUpdateInput";
import { NutritionPlan } from "./NutritionPlan";
import { TipFindManyArgs } from "../../tip/base/TipFindManyArgs";
import { Tip } from "../../tip/base/Tip";
@swagger.ApiBearerAuth()
export class NutritionPlanControllerBase {
  constructor(
    protected readonly service: NutritionPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: NutritionPlan })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: NutritionPlanCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"NutritionPlan"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        goal: data.goal
          ? {
              connect: data.goal,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        name: true,
        shoppingList: true,
        updatedAt: true,
        video: true,
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [NutritionPlan] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(NutritionPlanFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan[]> {
    const args = plainToClass(NutritionPlanFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "NutritionPlan",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        name: true,
        shoppingList: true,
        updatedAt: true,
        video: true,
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: NutritionPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "NutritionPlan",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        name: true,
        shoppingList: true,
        updatedAt: true,
        video: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: NutritionPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @common.Body()
    data: NutritionPlanUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"NutritionPlan"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          goal: data.goal
            ? {
                connect: data.goal,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          name: true,
          shoppingList: true,
          updatedAt: true,
          video: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: NutritionPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: NutritionPlanWhereUniqueInput
  ): Promise<NutritionPlan | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          name: true,
          shoppingList: true,
          updatedAt: true,
          video: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(TipFindManyArgs)
  async findManyTips(
    @common.Req() request: Request,
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Tip[]> {
    const query = plainToClass(TipFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tip",
    });
    const results = await this.service.findTips(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,

        nutritionPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        video: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "update",
    possession: "any",
  })
  async createTips(
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @common.Body() body: NutritionPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"NutritionPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "update",
    possession: "any",
  })
  async updateTips(
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @common.Body() body: NutritionPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"NutritionPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "NutritionPlan",
    action: "update",
    possession: "any",
  })
  async deleteTips(
    @common.Param() params: NutritionPlanWhereUniqueInput,
    @common.Body() body: NutritionPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "NutritionPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"NutritionPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
