/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateWorkoutPlanArgs } from "./CreateWorkoutPlanArgs";
import { UpdateWorkoutPlanArgs } from "./UpdateWorkoutPlanArgs";
import { DeleteWorkoutPlanArgs } from "./DeleteWorkoutPlanArgs";
import { WorkoutPlanFindManyArgs } from "./WorkoutPlanFindManyArgs";
import { WorkoutPlanFindUniqueArgs } from "./WorkoutPlanFindUniqueArgs";
import { WorkoutPlan } from "./WorkoutPlan";
import { TipFindManyArgs } from "../../tip/base/TipFindManyArgs";
import { Tip } from "../../tip/base/Tip";
import { WorkoutDayFindManyArgs } from "../../workoutDay/base/WorkoutDayFindManyArgs";
import { WorkoutDay } from "../../workoutDay/base/WorkoutDay";
import { Goal } from "../../goal/base/Goal";
import { Location } from "../../location/base/Location";
import { WorkoutPlanService } from "../workoutPlan.service";

@graphql.Resolver(() => WorkoutPlan)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class WorkoutPlanResolverBase {
  constructor(
    protected readonly service: WorkoutPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async _workoutPlansMeta(
    @graphql.Args() args: WorkoutPlanFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [WorkoutPlan])
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async workoutPlans(
    @graphql.Args() args: WorkoutPlanFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => WorkoutPlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "own",
  })
  async workoutPlan(
    @graphql.Args() args: WorkoutPlanFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "WorkoutPlan",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => WorkoutPlan)
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "create",
    possession: "any",
  })
  async createWorkoutPlan(
    @graphql.Args() args: CreateWorkoutPlanArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"WorkoutPlan"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        goal: args.data.goal
          ? {
              connect: args.data.goal,
            }
          : undefined,

        location: args.data.location
          ? {
              connect: args.data.location,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => WorkoutPlan)
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async updateWorkoutPlan(
    @graphql.Args() args: UpdateWorkoutPlanArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"WorkoutPlan"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          goal: args.data.goal
            ? {
                connect: args.data.goal,
              }
            : undefined,

          location: args.data.location
            ? {
                connect: args.data.location,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => WorkoutPlan)
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "delete",
    possession: "any",
  })
  async deleteWorkoutPlan(
    @graphql.Args() args: DeleteWorkoutPlanArgs
  ): Promise<WorkoutPlan | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Tip])
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async tips(
    @graphql.Parent() parent: WorkoutPlan,
    @graphql.Args() args: TipFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tip",
    });
    const results = await this.service.findTips(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [WorkoutDay])
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async workoutDays(
    @graphql.Parent() parent: WorkoutPlan,
    @graphql.Args() args: WorkoutDayFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutDay",
    });
    const results = await this.service.findWorkoutDays(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Goal, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async goal(
    @graphql.Parent() parent: WorkoutPlan,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Goal | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Goal",
    });
    const result = await this.service.getGoal(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Location, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  async location(
    @graphql.Parent() parent: WorkoutPlan,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Location | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Location",
    });
    const result = await this.service.getLocation(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
