/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkoutPlanService } from "../workoutPlan.service";
import { WorkoutPlanCreateInput } from "./WorkoutPlanCreateInput";
import { WorkoutPlanWhereInput } from "./WorkoutPlanWhereInput";
import { WorkoutPlanWhereUniqueInput } from "./WorkoutPlanWhereUniqueInput";
import { WorkoutPlanFindManyArgs } from "./WorkoutPlanFindManyArgs";
import { WorkoutPlanUpdateInput } from "./WorkoutPlanUpdateInput";
import { WorkoutPlan } from "./WorkoutPlan";
import { TipFindManyArgs } from "../../tip/base/TipFindManyArgs";
import { Tip } from "../../tip/base/Tip";
import { WorkoutDayFindManyArgs } from "../../workoutDay/base/WorkoutDayFindManyArgs";
import { WorkoutDay } from "../../workoutDay/base/WorkoutDay";
@swagger.ApiBearerAuth()
export class WorkoutPlanControllerBase {
  constructor(
    protected readonly service: WorkoutPlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: WorkoutPlan })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: WorkoutPlanCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"WorkoutPlan"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        goal: data.goal
          ? {
              connect: data.goal,
            }
          : undefined,

        location: data.location
          ? {
              connect: data.location,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,

        location: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
        video: true,
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [WorkoutPlan] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(WorkoutPlanFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan[]> {
    const args = plainToClass(WorkoutPlanFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,

        location: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
        video: true,
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: WorkoutPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "WorkoutPlan",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,

        goal: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,

        location: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
        video: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: WorkoutPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body()
    data: WorkoutPlanUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"WorkoutPlan"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          goal: data.goal
            ? {
                connect: data.goal,
              }
            : undefined,

          location: data.location
            ? {
                connect: data.location,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,

          location: {
            select: {
              id: true,
            },
          },

          name: true,
          updatedAt: true,
          video: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: WorkoutPlan })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: WorkoutPlanWhereUniqueInput
  ): Promise<WorkoutPlan | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,

          goal: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,

          location: {
            select: {
              id: true,
            },
          },

          name: true,
          updatedAt: true,
          video: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(TipFindManyArgs)
  async findManyTips(
    @common.Req() request: Request,
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Tip[]> {
    const query = plainToClass(TipFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tip",
    });
    const results = await this.service.findTips(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        image: true,
        name: true,

        nutritionPlan: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        video: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async createTips(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async updateTips(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/tips")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async deleteTips(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      tips: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/workoutDays")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(WorkoutDayFindManyArgs)
  async findManyWorkoutDays(
    @common.Req() request: Request,
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay[]> {
    const query = plainToClass(WorkoutDayFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutDay",
    });
    const results = await this.service.findWorkoutDays(params.id, {
      ...query,
      select: {
        createdAt: true,
        day: true,
        description: true,
        id: true,
        updatedAt: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/workoutDays")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async createWorkoutDays(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      workoutDays: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/workoutDays")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async updateWorkoutDays(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      workoutDays: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/workoutDays")
  @nestAccessControl.UseRoles({
    resource: "WorkoutPlan",
    action: "update",
    possession: "any",
  })
  async deleteWorkoutDays(
    @common.Param() params: WorkoutPlanWhereUniqueInput,
    @common.Body() body: WorkoutPlanWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      workoutDays: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutPlan"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
