/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { WorkoutDayWhereInput } from "./WorkoutDayWhereInput";
import { Type } from "class-transformer";
import { WorkoutDayOrderByInput } from "./WorkoutDayOrderByInput";

@ArgsType()
class WorkoutDayFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => WorkoutDayWhereInput,
  })
  @Field(() => WorkoutDayWhereInput, { nullable: true })
  @Type(() => WorkoutDayWhereInput)
  where?: WorkoutDayWhereInput;

  @ApiProperty({
    required: false,
    type: WorkoutDayOrderByInput,
  })
  @Field(() => WorkoutDayOrderByInput, { nullable: true })
  @Type(() => WorkoutDayOrderByInput)
  orderBy?: WorkoutDayOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { WorkoutDayFindManyArgs };
