/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WorkoutDayService } from "../workoutDay.service";
import { WorkoutDayCreateInput } from "./WorkoutDayCreateInput";
import { WorkoutDayWhereInput } from "./WorkoutDayWhereInput";
import { WorkoutDayWhereUniqueInput } from "./WorkoutDayWhereUniqueInput";
import { WorkoutDayFindManyArgs } from "./WorkoutDayFindManyArgs";
import { WorkoutDayUpdateInput } from "./WorkoutDayUpdateInput";
import { WorkoutDay } from "./WorkoutDay";
import { ExerciseFindManyArgs } from "../../exercise/base/ExerciseFindManyArgs";
import { Exercise } from "../../exercise/base/Exercise";
@swagger.ApiBearerAuth()
export class WorkoutDayControllerBase {
  constructor(
    protected readonly service: WorkoutDayService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: WorkoutDay })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: WorkoutDayCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "WorkoutDay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"WorkoutDay"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        workoutPlan: data.workoutPlan
          ? {
              connect: data.workoutPlan,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        day: true,
        description: true,
        id: true,
        updatedAt: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [WorkoutDay] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(WorkoutDayFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay[]> {
    const args = plainToClass(WorkoutDayFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutDay",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        day: true,
        description: true,
        id: true,
        updatedAt: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: WorkoutDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "WorkoutDay",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        day: true,
        description: true,
        id: true,
        updatedAt: true,

        workoutPlan: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: WorkoutDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @common.Body()
    data: WorkoutDayUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<WorkoutDay | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutDay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"WorkoutDay"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          workoutPlan: data.workoutPlan
            ? {
                connect: data.workoutPlan,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          day: true,
          description: true,
          id: true,
          updatedAt: true,

          workoutPlan: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: WorkoutDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: WorkoutDayWhereUniqueInput
  ): Promise<WorkoutDay | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          day: true,
          description: true,
          id: true,
          updatedAt: true,

          workoutPlan: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "read",
    possession: "any",
  })
  @ApiNestedQuery(ExerciseFindManyArgs)
  async findManyExercises(
    @common.Req() request: Request,
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Exercise[]> {
    const query = plainToClass(ExerciseFindManyArgs, request.query);
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Exercise",
    });
    const results = await this.service.findExercises(params.id, {
      ...query,
      select: {
        additionalInformation: true,
        createdAt: true,
        description: true,
        duration: true,
        exerciseType: true,
        id: true,
        image: true,
        name: true,
        repetitions: true,
        sets: true,
        updatedAt: true,
        video: true,

        workoutDay: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "update",
    possession: "any",
  })
  async createExercises(
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @common.Body() body: WorkoutDayWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      exercises: {
        connect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutDay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutDay"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "update",
    possession: "any",
  })
  async updateExercises(
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @common.Body() body: WorkoutDayWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      exercises: {
        set: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutDay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutDay"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id/exercises")
  @nestAccessControl.UseRoles({
    resource: "WorkoutDay",
    action: "update",
    possession: "any",
  })
  async deleteExercises(
    @common.Param() params: WorkoutDayWhereUniqueInput,
    @common.Body() body: WorkoutDayWhereUniqueInput[],
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<void> {
    const data = {
      exercises: {
        disconnect: body,
      },
    };
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "WorkoutDay",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new common.ForbiddenException(
        `Updating the relationship: ${
          invalidAttributes[0]
        } of ${"WorkoutDay"} is forbidden for roles: ${roles}`
      );
    }
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
