/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsInt,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { EnumExerciseExerciseType } from "./EnumExerciseExerciseType";
import { WorkoutDayWhereUniqueInput } from "../../workoutDay/base/WorkoutDayWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class ExerciseCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  additionalInformation?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  duration?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumExerciseExerciseType,
  })
  @IsEnum(EnumExerciseExerciseType)
  @IsOptional()
  @Field(() => EnumExerciseExerciseType, {
    nullable: true,
  })
  exerciseType?: "TIME" | "SET" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  repetitions?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  sets?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  video?: string | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutDayWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkoutDayWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkoutDayWhereUniqueInput, {
    nullable: true,
  })
  workoutDay?: WorkoutDayWhereUniqueInput | null;
}
export { ExerciseCreateInput };
