/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ExerciseService } from "../exercise.service";
import { ExerciseCreateInput } from "./ExerciseCreateInput";
import { ExerciseWhereInput } from "./ExerciseWhereInput";
import { ExerciseWhereUniqueInput } from "./ExerciseWhereUniqueInput";
import { ExerciseFindManyArgs } from "./ExerciseFindManyArgs";
import { ExerciseUpdateInput } from "./ExerciseUpdateInput";
import { Exercise } from "./Exercise";
@swagger.ApiBearerAuth()
export class ExerciseControllerBase {
  constructor(
    protected readonly service: ExerciseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Exercise })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ExerciseCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Exercise> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Exercise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Exercise"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        workoutDay: data.workoutDay
          ? {
              connect: data.workoutDay,
            }
          : undefined,
      },
      select: {
        additionalInformation: true,
        createdAt: true,
        description: true,
        duration: true,
        exerciseType: true,
        id: true,
        image: true,
        name: true,
        repetitions: true,
        sets: true,
        updatedAt: true,
        video: true,

        workoutDay: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [Exercise] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ExerciseFindManyArgs)
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Exercise[]> {
    const args = plainToClass(ExerciseFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Exercise",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        additionalInformation: true,
        createdAt: true,
        description: true,
        duration: true,
        exerciseType: true,
        id: true,
        image: true,
        name: true,
        repetitions: true,
        sets: true,
        updatedAt: true,
        video: true,

        workoutDay: {
          select: {
            id: true,
          },
        },
      },
    });
    return results.map((result) => permission.filter(result));
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ExerciseWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Exercise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Exercise",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        additionalInformation: true,
        createdAt: true,
        description: true,
        duration: true,
        exerciseType: true,
        id: true,
        image: true,
        name: true,
        repetitions: true,
        sets: true,
        updatedAt: true,
        video: true,

        workoutDay: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ExerciseWhereUniqueInput,
    @common.Body()
    data: ExerciseUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Exercise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Exercise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Exercise"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          workoutDay: data.workoutDay
            ? {
                connect: data.workoutDay,
              }
            : undefined,
        },
        select: {
          additionalInformation: true,
          createdAt: true,
          description: true,
          duration: true,
          exerciseType: true,
          id: true,
          image: true,
          name: true,
          repetitions: true,
          sets: true,
          updatedAt: true,
          video: true,

          workoutDay: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Exercise })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ExerciseWhereUniqueInput
  ): Promise<Exercise | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          additionalInformation: true,
          createdAt: true,
          description: true,
          duration: true,
          exerciseType: true,
          id: true,
          image: true,
          name: true,
          repetitions: true,
          sets: true,
          updatedAt: true,
          video: true,

          workoutDay: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
