/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateTipArgs } from "./CreateTipArgs";
import { UpdateTipArgs } from "./UpdateTipArgs";
import { DeleteTipArgs } from "./DeleteTipArgs";
import { TipFindManyArgs } from "./TipFindManyArgs";
import { TipFindUniqueArgs } from "./TipFindUniqueArgs";
import { Tip } from "./Tip";
import { NutritionPlan } from "../../nutritionPlan/base/NutritionPlan";
import { WorkoutPlan } from "../../workoutPlan/base/WorkoutPlan";
import { TipService } from "../tip.service";

@graphql.Resolver(() => Tip)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TipResolverBase {
  constructor(
    protected readonly service: TipService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "read",
    possession: "any",
  })
  async _tipsMeta(
    @graphql.Args() args: TipFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Tip])
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "read",
    possession: "any",
  })
  async tips(
    @graphql.Args() args: TipFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Tip",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Tip, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "read",
    possession: "own",
  })
  async tip(
    @graphql.Args() args: TipFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Tip",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Tip)
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "create",
    possession: "any",
  })
  async createTip(
    @graphql.Args() args: CreateTipArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Tip",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Tip"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        nutritionPlan: args.data.nutritionPlan
          ? {
              connect: args.data.nutritionPlan,
            }
          : undefined,

        workoutPlan: args.data.workoutPlan
          ? {
              connect: args.data.workoutPlan,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Tip)
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "update",
    possession: "any",
  })
  async updateTip(
    @graphql.Args() args: UpdateTipArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Tip | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Tip",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Tip"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          nutritionPlan: args.data.nutritionPlan
            ? {
                connect: args.data.nutritionPlan,
              }
            : undefined,

          workoutPlan: args.data.workoutPlan
            ? {
                connect: args.data.workoutPlan,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tip)
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "delete",
    possession: "any",
  })
  async deleteTip(@graphql.Args() args: DeleteTipArgs): Promise<Tip | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => NutritionPlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "read",
    possession: "any",
  })
  async nutritionPlan(
    @graphql.Parent() parent: Tip,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<NutritionPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "NutritionPlan",
    });
    const result = await this.service.getNutritionPlan(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => WorkoutPlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Tip",
    action: "read",
    possession: "any",
  })
  async workoutPlan(
    @graphql.Parent() parent: Tip,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<WorkoutPlan | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "WorkoutPlan",
    });
    const result = await this.service.getWorkoutPlan(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
