/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { TipWhereInput } from "./TipWhereInput";
import { Type } from "class-transformer";
import { TipOrderByInput } from "./TipOrderByInput";

@ArgsType()
class TipFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => TipWhereInput,
  })
  @Field(() => TipWhereInput, { nullable: true })
  @Type(() => TipWhereInput)
  where?: TipWhereInput;

  @ApiProperty({
    required: false,
    type: TipOrderByInput,
  })
  @Field(() => TipOrderByInput, { nullable: true })
  @Type(() => TipOrderByInput)
  orderBy?: TipOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { TipFindManyArgs };
