/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { NutritionPlanWhereUniqueInput } from "../../nutritionPlan/base/NutritionPlanWhereUniqueInput";
import { Type } from "class-transformer";
import { WorkoutPlanWhereUniqueInput } from "../../workoutPlan/base/WorkoutPlanWhereUniqueInput";
@InputType()
class TipUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NutritionPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => NutritionPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => NutritionPlanWhereUniqueInput, {
    nullable: true,
  })
  nutritionPlan?: NutritionPlanWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  video?: string | null;

  @ApiProperty({
    required: false,
    type: () => WorkoutPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkoutPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkoutPlanWhereUniqueInput, {
    nullable: true,
  })
  workoutPlan?: WorkoutPlanWhereUniqueInput | null;
}
export { TipUpdateInput };
