/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { NutritionPlanWhereUniqueInput } from "../../nutritionPlan/base/NutritionPlanWhereUniqueInput";
import { WorkoutPlanWhereUniqueInput } from "../../workoutPlan/base/WorkoutPlanWhereUniqueInput";
@InputType()
class TipWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  image?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => NutritionPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => NutritionPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => NutritionPlanWhereUniqueInput, {
    nullable: true,
  })
  nutritionPlan?: NutritionPlanWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  video?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => WorkoutPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => WorkoutPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => WorkoutPlanWhereUniqueInput, {
    nullable: true,
  })
  workoutPlan?: WorkoutPlanWhereUniqueInput;
}
export { TipWhereInput };
